import type { Metadata } from "next";
import { photographyNameFont, technologyNameFont, photographySubHeaderFont, aboutPhotographyText } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${photographyNameFont.variable} ${technologyNameFont.variable} ${photographySubHeaderFont.variable} ${aboutPhotographyText.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
