import type { Metadata } from "next";
import {
  photographyNameFont, technologyNameFont,
  photographySubHeaderFont, aboutPhotographyText,
  technologySubHeaderFont, technologyF1, technologyF2, technologyF3
} from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${photographyNameFont.variable} ${technologyNameFont.variable}
        ${photographySubHeaderFont.variable} ${aboutPhotographyText.variable} ${technologySubHeaderFont.variable}
        ${technologyF1.variable} ${technologyF2.variable} ${technologyF3.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
